#!/bin/sh
ROOTFS_URL=https://alpha.de.repo.voidlinux.org/live/current/void-x86_64-ROOTFS-20191109.tar.xz
ESSENTIAL_SOFT="opendoas git dhcpcd";
USERSPACE_SOFT="xorg vim cmus lf zathura dmenu curl jq base-devel tcc go dunst firefox kpcli youtube-dl";
DEV_SOFT="go tcc base-devel";
TEXLIVE="texlive-most texlive-lang";

USERNAME=

choice() {
   PROMPT="$1";
   printf "%s[Y/n]: " "$PROMPT";
   read -r CHOICE;
   case "$CHOICE" in
      [Yy]* ) true  ;;
      [Nn]* ) false ;;
   esac
}

title() {
   TITLE=$*; 
   TITLELEN=$(echo "$TITLE" | wc -m);
   
   printlen() {
      for f in $(seq 2 "$TITLELEN"); do
         printf "-";
      done 
      printf "\n";
   }
   printlen;
   echo "$TITLE";
   printlen;
}
welcome() {
   title "start - installation script";
}
getrootfs() {
   title "GET ROOTFS";
	xbps-install -y xz;
	wget $ROOTFS_URL;
	tar xvf void-*;
	rm void-*;	
}
prepchroot() {
   title "CHROOT";
   mount --rbind /sys /mnt/sys && mount --make-rslave /mnt/sys;
   mount --rbind /dev /mnt/dev && mount --make-rslave /mnt/dev;
   mount --rbind /proc /mnt/proc && mount --make-rslave /mnt/proc;

   cp /etc/resolv.conf /mnt/etc;

   PS1='(chroot) # ' chroot /mnt /bin/bash; # HAHAHAHAHAHAHAHAHAHAHAHAHAHAHA, that is funny.
}
installbasesystem() {
   title "INSTALL BASE SYSTEM PACKAGE";
   xbps-install -Suy xbps;
   xbps-install -uy;
   xbps-install -y base-system;
   xbps-remove -y base-voidstrap;
}
passwdset() {
   title "SET ROOT PASSWORD"; 
   passwd;
}
hostnameset() {
   title "SET HOSTNAME";
   read -r HOSTNAME ;
   echo "$HOSTNAME" > /etc/hostname;
}
setlocale() {
   title "SET LOCALE";
   echo "en_US.UTF-8 UTF-8" >> /etc/default/libc-locales;
   xbps-reconfigure -f glibc-locales;
}
genfstab() {
   title "GEN FSTAB";
   grep -v 'cgroup' /proc/mounts | \
   grep -v 'sysfs' | \
   grep -v 'proc' | \
   grep -v 'tmpfs' | \
   grep -v 'securityfs' | \
   grep -v 'devpts' >> /etc/fstab;
}
installgrub() {
   title "INSTALL GRUB";
   xbps-install -y grub;
   printf "Where to install GRUB: ";
   read -r GRUBINSTALL;
   grub-install "$GRUBINSTALL";
}
installsoft() {
   title "INSTALL USERSPACE SOFTWARE";
   xbps-install -y $ESSENTIAL_SOFT $USERSPACE_SOFT;
}
installtexlive() {
   title "INSTALL TEXLIVE";
   xbps-install -y $TEXLIVE;
}
installdev() {
   title "INSTALL BASE DEVEL";
   printf "install base devel and other compilers[Y/n]:"
   read -r INSTALLDEV;
   if choice "$INSTALLDEV"; then
      xbps-install -y $DEV_SOFT
   fi
}
setupdoas() {
   title "SETUP DOAS";
   echo "permit :wheel" > /etc/doas.conf
}
createuser() {
   title "CREATE AND SWITCH TO USER";    
   printf "Enter username: ";
   read -r USERNAME; 
   useradd -m -G wheel "$USERNAME"; 
   export USERNAME;
   passwd "$USERNAME";
   su - "$USERNAME";
}
dotfiles() {
   title "DOTFILES CONFIGURATION"; 
	git clone "https://github.com/ykmv/dotfiles";
	cd ~/dotfiles;
	sh symlinks.sh;
}
installsuckless() {
   title "INSTALL SUCKLESS SOFTWARE";
	mkdir ~/suckless;
	makesoft() {
	   git clone https://github.com/ykmv/"$1" ~/suckless/"$1";
	   cd ~/suckless/"$1";
	   make;
	   doas make install;
	}
	makesoft dwm;
	makesoft st;
}

cd /mnt || exit;
welcome;
getrootfs;
prepchroot;
PS1='(chroot) # ' chroot /mnt /bin/bash << EOF # HAHAHAHAHAHAHAHAHAHAHAHAHAHAHA, that is funny.
installbasesystem;
hostnameset;
setlocale;
passwdset;
genfstab;
if choice "Install GRUB"; then installgrub; fi
if choice "Install Essential and Userspace software"; then installsoft; fi
if choice "Install Texlive packages"; then installtexlive; fi
if choice "Install base-devel and other toolchains"; then installdev; fi
setupdoas;
createuser;
if choice "Install Dotfiles"; then dotfiles; fi
if choice "Install Suckless software"; then installsuckless; fi
EOF
exit;
exit;
reboot;
